set_clock_latency -source -early -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  1.75652 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -min -fall  1.74743 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -min -rise  1.75652 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -min -fall  1.74743 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.181609 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.18985 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
