set_clock_latency -source -early -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -max -rise  1.49223 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -max -fall  1.48896 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -max -rise  1.49223 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -max -fall  1.48896 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -early -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -max -rise  -0.381774 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -max -fall  -0.391702 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
